name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "${{ matrix.os }}-${{ matrix.build }}"
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            build: Release
          - os: ubuntu-22.04
            build: Debug
          - os: macos-14
            build: Release

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies (linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install \
            ocl-icd-opencl-dev \
            libfmt-dev \
            lcov

      - name: Install dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install \
            cmake \
            fmt \
            lcov

      - name: Configure
        run: |
          cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
            -DOPENCLCPP_LITE_BUILD_TESTS=YES \
            -DOPENCLCPP_LITE_CODE_COVERAGE=YES

      - name: Build
        run: cmake --build ${{ github.workspace }}/build
